# Generated by Django 4.2 on 2024-10-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_onetimepassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepassword',
            old_name='code',
            new_name='otp',
        ),
    ]
