# Generated by Django 4.2 on 2024-10-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_code_onetimepassword_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('content_creator', 'Content Creator'), ('reader', 'Reader')], default='Reader', max_length=20),
        ),
    ]
